#!/bin/sh
# Regenerates assets/wordlist.js from the dicio-pt-br submodule.
#
# Source: dicio-pt-br/icf  -> ~419k words sorted most-common-first (Inverse
#         Corpus Frequency). We keep the most common words that make good,
#         memorable passphrase tokens.
# Blocklist: dicio-pt-br/listas/negativas -> offensive words to drop.
#
# Filter: lowercase alpha (incl. pt-BR accents) words of 4-8 letters, dedup,
#         blocklist removed, then take the first COUNT (diceware size).
#
# Run from the repo root:  sh scripts/build-wordlist.sh
set -eu

COUNT=7776
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
ICF="$ROOT/dicio-pt-br/icf"
BLOCK="$ROOT/dicio-pt-br/listas/negativas"
OUT="$ROOT/assets/wordlist.js"

if [ ! -f "$ICF" ]; then
  echo "error: $ICF not found. Did you init the git submodule?" >&2
  echo "  git submodule update --init --recursive" >&2
  exit 1
fi

TMP="$(mktemp "${TMPDIR:-/tmp}/wordlist.XXXXXX")"
BLK="$(mktemp "${TMPDIR:-/tmp}/blocklist.XXXXXX")"
trap 'rm -f "$TMP" "$BLK"' EXIT

# 4-8 letter offensive words, one per line, sorted+unique.
grep -ixE '[a-zà-ÿ]{4,8}' "$BLOCK" | sort -u > "$BLK"

# Most-common-first -> filter length/alpha -> drop blocklist -> dedup -> take COUNT.
awk -F, '{print $1}' "$ICF" \
  | grep -ixE '[a-zà-ÿ]{4,8}' \
  | awk 'NR==FNR{b[$0];next} ($0 in b){next} seen[$0]++==0' "$BLK" - \
  | head -"$COUNT" > "$TMP"

N="$(wc -l < "$TMP" | tr -d ' ')"
if [ "$N" -ne "$COUNT" ]; then
  echo "error: only produced $N words (wanted $COUNT)" >&2
  exit 1
fi

# Emit as a JS global. One word per array entry, comma-separated, wrapped.
{
  echo "// Generated by scripts/build-wordlist.sh — do not edit by hand."
  echo "// $COUNT most-common pt-BR words (4-8 letters) from the dicio-pt-br corpus."
  echo "// log2($COUNT) ≈ 12.925 bits of entropy per word."
  printf 'window.WORDLIST=['
  awk '{printf "%s\"%s\"", (NR>1?",":""), $0}' "$TMP"
  echo '];'
} > "$OUT"

echo "wrote $N words to $OUT"
